// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: forge/v1/forge.proto

package forgev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Settings      map[string]string      `protobuf:"bytes,3,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_forge_v1_forge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_forge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_forge_v1_forge_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigureRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ConfigureRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ConfigureRequest) GetSettings() map[string]string {
	if x != nil {
		return x.Settings
	}
	return nil
}

type ConfigureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_forge_v1_forge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_forge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_forge_v1_forge_proto_rawDescGZIP(), []int{1}
}

type RepoRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Repo          string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepoRef) Reset() {
	*x = RepoRef{}
	mi := &file_forge_v1_forge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepoRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoRef) ProtoMessage() {}

func (x *RepoRef) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_forge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoRef.ProtoReflect.Descriptor instead.
func (*RepoRef) Descriptor() ([]byte, []int) {
	return file_forge_v1_forge_proto_rawDescGZIP(), []int{2}
}

func (x *RepoRef) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *RepoRef) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

type PullRequestRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          *RepoRef               `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Number        int32                  `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullRequestRef) Reset() {
	*x = PullRequestRef{}
	mi := &file_forge_v1_forge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullRequestRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRequestRef) ProtoMessage() {}

func (x *PullRequestRef) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_forge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullRequestRef.ProtoReflect.Descriptor instead.
func (*PullRequestRef) Descriptor() ([]byte, []int) {
	return file_forge_v1_forge_proto_rawDescGZIP(), []int{3}
}

func (x *PullRequestRef) GetRepo() *RepoRef {
	if x != nil {
		return x.Repo
	}
	return nil
}

func (x *PullRequestRef) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type Issue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int32                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Labels        []string               `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Issue) Reset() {
	*x = Issue{}
	mi := &file_forge_v1_forge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Issue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Issue) ProtoMessage() {}

func (x *Issue) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_forge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Issue.ProtoReflect.Descriptor instead.
func (*Issue) Descriptor() ([]byte, []int) {
	return file_forge_v1_forge_proto_rawDescGZIP(), []int{4}
}

func (x *Issue) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Issue) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Issue) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Issue) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type AssignedIssuesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issues        []*Issue               `protobuf:"bytes,1,rep,name=issues,proto3" json:"issues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignedIssuesResponse) Reset() {
	*x = AssignedIssuesResponse{}
	mi := &file_forge_v1_forge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignedIssuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignedIssuesResponse) ProtoMessage() {}

func (x *AssignedIssuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_forge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignedIssuesResponse.ProtoReflect.Descriptor instead.
func (*AssignedIssuesResponse) Descriptor() ([]byte, []int) {
	return file_forge_v1_forge_proto_rawDescGZIP(), []int{5}
}

func (x *AssignedIssuesResponse) GetIssues() []*Issue {
	if x != nil {
		return x.Issues
	}
	return nil
}

type IssuesWithLabelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issues        []*Issue               `protobuf:"bytes,1,rep,name=issues,proto3" json:"issues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssuesWithLabelResponse) Reset() {
	*x = IssuesWithLabelResponse{}
	mi := &file_forge_v1_forge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssuesWithLabelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuesWithLabelResponse) ProtoMessage() {}

func (x *IssuesWithLabelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_forge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssuesWithLabelResponse.ProtoReflect.Descriptor instead.
func (*IssuesWithLabelResponse) Descriptor() ([]byte, []int) {
	return file_forge_v1_forge_proto_rawDescGZIP(), []int{6}
}

func (x *IssuesWithLabelResponse) GetIssues() []*Issue {
	if x != nil {
		return x.Issues
	}
	return nil
}

type AssignedIssuesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          *RepoRef               `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Assignee      string                 `protobuf:"bytes,2,opt,name=assignee,proto3" json:"assignee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignedIssuesRequest) Reset() {
	*x = AssignedIssuesRequest{}
	mi := &file_forge_v1_forge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignedIssuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignedIssuesRequest) ProtoMessage() {}

func (x *AssignedIssuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_forge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignedIssuesRequest.ProtoReflect.Descriptor instead.
func (*AssignedIssuesRequest) Descriptor() ([]byte, []int) {
	return file_forge_v1_forge_proto_rawDescGZIP(), []int{7}
}

func (x *AssignedIssuesRequest) GetRepo() *RepoRef {
	if x != nil {
		return x.Repo
	}
	return nil
}

func (x *AssignedIssuesRequest) GetAssignee() string {
	if x != nil {
		return x.Assignee
	}
	return ""
}

type IssuesWithLabelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          *RepoRef               `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssuesWithLabelRequest) Reset() {
	*x = IssuesWithLabelRequest{}
	mi := &file_forge_v1_forge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssuesWithLabelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuesWithLabelRequest) ProtoMessage() {}

func (x *IssuesWithLabelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_forge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssuesWithLabelRequest.ProtoReflect.Descriptor instead.
func (*IssuesWithLabelRequest) Descriptor() ([]byte, []int) {
	return file_forge_v1_forge_proto_rawDescGZIP(), []int{8}
}

func (x *IssuesWithLabelRequest) GetRepo() *RepoRef {
	if x != nil {
		return x.Repo
	}
	return nil
}

func (x *IssuesWithLabelRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type CommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          *RepoRef               `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Number        int32                  `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentRequest) Reset() {
	*x = CommentRequest{}
	mi := &file_forge_v1_forge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentRequest) ProtoMessage() {}

func (x *CommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_forge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentRequest.ProtoReflect.Descriptor instead.
func (*CommentRequest) Descriptor() ([]byte, []int) {
	return file_forge_v1_forge_proto_rawDescGZIP(), []int{9}
}

func (x *CommentRequest) GetRepo() *RepoRef {
	if x != nil {
		return x.Repo
	}
	return nil
}

func (x *CommentRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *CommentRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type CommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentResponse) Reset() {
	*x = CommentResponse{}
	mi := &file_forge_v1_forge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentResponse) ProtoMessage() {}

func (x *CommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_forge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentResponse.ProtoReflect.Descriptor instead.
func (*CommentResponse) Descriptor() ([]byte, []int) {
	return file_forge_v1_forge_proto_rawDescGZIP(), []int{10}
}

func (x *CommentResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CloseIssueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          *RepoRef               `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Number        int32                  `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Comment       string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseIssueRequest) Reset() {
	*x = CloseIssueRequest{}
	mi := &file_forge_v1_forge_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseIssueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseIssueRequest) ProtoMessage() {}

func (x *CloseIssueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_forge_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseIssueRequest.ProtoReflect.Descriptor instead.
func (*CloseIssueRequest) Descriptor() ([]byte, []int) {
	return file_forge_v1_forge_proto_rawDescGZIP(), []int{11}
}

func (x *CloseIssueRequest) GetRepo() *RepoRef {
	if x != nil {
		return x.Repo
	}
	return nil
}

func (x *CloseIssueRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *CloseIssueRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type CloseIssueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseIssueResponse) Reset() {
	*x = CloseIssueResponse{}
	mi := &file_forge_v1_forge_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseIssueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseIssueResponse) ProtoMessage() {}

func (x *CloseIssueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_forge_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseIssueResponse.ProtoReflect.Descriptor instead.
func (*CloseIssueResponse) Descriptor() ([]byte, []int) {
	return file_forge_v1_forge_proto_rawDescGZIP(), []int{12}
}

type ReactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          *RepoRef               `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Number        int32                  `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Reaction      string                 `protobuf:"bytes,3,opt,name=reaction,proto3" json:"reaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReactRequest) Reset() {
	*x = ReactRequest{}
	mi := &file_forge_v1_forge_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactRequest) ProtoMessage() {}

func (x *ReactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_forge_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactRequest.ProtoReflect.Descriptor instead.
func (*ReactRequest) Descriptor() ([]byte, []int) {
	return file_forge_v1_forge_proto_rawDescGZIP(), []int{13}
}

func (x *ReactRequest) GetRepo() *RepoRef {
	if x != nil {
		return x.Repo
	}
	return nil
}

func (x *ReactRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *ReactRequest) GetReaction() string {
	if x != nil {
		return x.Reaction
	}
	return ""
}

type ReactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReactResponse) Reset() {
	*x = ReactResponse{}
	mi := &file_forge_v1_forge_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactResponse) ProtoMessage() {}

func (x *ReactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_forge_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactResponse.ProtoReflect.Descriptor instead.
func (*ReactResponse) Descriptor() ([]byte, []int) {
	return file_forge_v1_forge_proto_rawDescGZIP(), []int{14}
}

type SetStateLabelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          *RepoRef               `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Number        int32                  `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	KnownLabels   []string               `protobuf:"bytes,4,rep,name=known_labels,json=knownLabels,proto3" json:"known_labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStateLabelRequest) Reset() {
	*x = SetStateLabelRequest{}
	mi := &file_forge_v1_forge_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStateLabelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStateLabelRequest) ProtoMessage() {}

func (x *SetStateLabelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_forge_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStateLabelRequest.ProtoReflect.Descriptor instead.
func (*SetStateLabelRequest) Descriptor() ([]byte, []int) {
	return file_forge_v1_forge_proto_rawDescGZIP(), []int{15}
}

func (x *SetStateLabelRequest) GetRepo() *RepoRef {
	if x != nil {
		return x.Repo
	}
	return nil
}

func (x *SetStateLabelRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *SetStateLabelRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SetStateLabelRequest) GetKnownLabels() []string {
	if x != nil {
		return x.KnownLabels
	}
	return nil
}

type SetStateLabelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStateLabelResponse) Reset() {
	*x = SetStateLabelResponse{}
	mi := &file_forge_v1_forge_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStateLabelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStateLabelResponse) ProtoMessage() {}

func (x *SetStateLabelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_forge_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStateLabelResponse.ProtoReflect.Descriptor instead.
func (*SetStateLabelResponse) Descriptor() ([]byte, []int) {
	return file_forge_v1_forge_proto_rawDescGZIP(), []int{16}
}

type CreatePRRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          *RepoRef               `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Head          string                 `protobuf:"bytes,3,opt,name=head,proto3" json:"head,omitempty"`
	Base          string                 `protobuf:"bytes,4,opt,name=base,proto3" json:"base,omitempty"`
	Body          string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePRRequest) Reset() {
	*x = CreatePRRequest{}
	mi := &file_forge_v1_forge_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePRRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePRRequest) ProtoMessage() {}

func (x *CreatePRRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_forge_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePRRequest.ProtoReflect.Descriptor instead.
func (*CreatePRRequest) Descriptor() ([]byte, []int) {
	return file_forge_v1_forge_proto_rawDescGZIP(), []int{17}
}

func (x *CreatePRRequest) GetRepo() *RepoRef {
	if x != nil {
		return x.Repo
	}
	return nil
}

func (x *CreatePRRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePRRequest) GetHead() string {
	if x != nil {
		return x.Head
	}
	return ""
}

func (x *CreatePRRequest) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *CreatePRRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type CreatePRResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int32                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePRResponse) Reset() {
	*x = CreatePRResponse{}
	mi := &file_forge_v1_forge_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePRResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePRResponse) ProtoMessage() {}

func (x *CreatePRResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_forge_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePRResponse.ProtoReflect.Descriptor instead.
func (*CreatePRResponse) Descriptor() ([]byte, []int) {
	return file_forge_v1_forge_proto_rawDescGZIP(), []int{18}
}

func (x *CreatePRResponse) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type PRStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          *RepoRef               `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Number        int32                  `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PRStateRequest) Reset() {
	*x = PRStateRequest{}
	mi := &file_forge_v1_forge_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PRStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PRStateRequest) ProtoMessage() {}

func (x *PRStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_forge_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PRStateRequest.ProtoReflect.Descriptor instead.
func (*PRStateRequest) Descriptor() ([]byte, []int) {
	return file_forge_v1_forge_proto_rawDescGZIP(), []int{19}
}

func (x *PRStateRequest) GetRepo() *RepoRef {
	if x != nil {
		return x.Repo
	}
	return nil
}

func (x *PRStateRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type PRStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PRStateResponse) Reset() {
	*x = PRStateResponse{}
	mi := &file_forge_v1_forge_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PRStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PRStateResponse) ProtoMessage() {}

func (x *PRStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_forge_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PRStateResponse.ProtoReflect.Descriptor instead.
func (*PRStateResponse) Descriptor() ([]byte, []int) {
	return file_forge_v1_forge_proto_rawDescGZIP(), []int{20}
}

func (x *PRStateResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type PullRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int32                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	HeadRef       string                 `protobuf:"bytes,4,opt,name=head_ref,json=headRef,proto3" json:"head_ref,omitempty"`
	BaseRef       string                 `protobuf:"bytes,5,opt,name=base_ref,json=baseRef,proto3" json:"base_ref,omitempty"`
	HeadSha       string                 `protobuf:"bytes,6,opt,name=head_sha,json=headSha,proto3" json:"head_sha,omitempty"`
	BaseSha       string                 `protobuf:"bytes,7,opt,name=base_sha,json=baseSha,proto3" json:"base_sha,omitempty"`
	State         string                 `protobuf:"bytes,8,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullRequest) Reset() {
	*x = PullRequest{}
	mi := &file_forge_v1_forge_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRequest) ProtoMessage() {}

func (x *PullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_forge_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullRequest.ProtoReflect.Descriptor instead.
func (*PullRequest) Descriptor() ([]byte, []int) {
	return file_forge_v1_forge_proto_rawDescGZIP(), []int{21}
}

func (x *PullRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *PullRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PullRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *PullRequest) GetHeadRef() string {
	if x != nil {
		return x.HeadRef
	}
	return ""
}

func (x *PullRequest) GetBaseRef() string {
	if x != nil {
		return x.BaseRef
	}
	return ""
}

func (x *PullRequest) GetHeadSha() string {
	if x != nil {
		return x.HeadSha
	}
	return ""
}

func (x *PullRequest) GetBaseSha() string {
	if x != nil {
		return x.BaseSha
	}
	return ""
}

func (x *PullRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type GetPullRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          *RepoRef               `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Number        int32                  `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPullRequestRequest) Reset() {
	*x = GetPullRequestRequest{}
	mi := &file_forge_v1_forge_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPullRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPullRequestRequest) ProtoMessage() {}

func (x *GetPullRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_forge_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPullRequestRequest.ProtoReflect.Descriptor instead.
func (*GetPullRequestRequest) Descriptor() ([]byte, []int) {
	return file_forge_v1_forge_proto_rawDescGZIP(), []int{22}
}

func (x *GetPullRequestRequest) GetRepo() *RepoRef {
	if x != nil {
		return x.Repo
	}
	return nil
}

func (x *GetPullRequestRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type GetPullRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PullRequest   *PullRequest           `protobuf:"bytes,1,opt,name=pull_request,json=pullRequest,proto3" json:"pull_request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPullRequestResponse) Reset() {
	*x = GetPullRequestResponse{}
	mi := &file_forge_v1_forge_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPullRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPullRequestResponse) ProtoMessage() {}

func (x *GetPullRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_forge_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPullRequestResponse.ProtoReflect.Descriptor instead.
func (*GetPullRequestResponse) Descriptor() ([]byte, []int) {
	return file_forge_v1_forge_proto_rawDescGZIP(), []int{23}
}

func (x *GetPullRequestResponse) GetPullRequest() *PullRequest {
	if x != nil {
		return x.PullRequest
	}
	return nil
}

type GetPullRequestDiffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          *RepoRef               `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Number        int32                  `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPullRequestDiffRequest) Reset() {
	*x = GetPullRequestDiffRequest{}
	mi := &file_forge_v1_forge_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPullRequestDiffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPullRequestDiffRequest) ProtoMessage() {}

func (x *GetPullRequestDiffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_forge_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPullRequestDiffRequest.ProtoReflect.Descriptor instead.
func (*GetPullRequestDiffRequest) Descriptor() ([]byte, []int) {
	return file_forge_v1_forge_proto_rawDescGZIP(), []int{24}
}

func (x *GetPullRequestDiffRequest) GetRepo() *RepoRef {
	if x != nil {
		return x.Repo
	}
	return nil
}

func (x *GetPullRequestDiffRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type GetPullRequestDiffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Diff          string                 `protobuf:"bytes,1,opt,name=diff,proto3" json:"diff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPullRequestDiffResponse) Reset() {
	*x = GetPullRequestDiffResponse{}
	mi := &file_forge_v1_forge_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPullRequestDiffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPullRequestDiffResponse) ProtoMessage() {}

func (x *GetPullRequestDiffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_forge_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPullRequestDiffResponse.ProtoReflect.Descriptor instead.
func (*GetPullRequestDiffResponse) Descriptor() ([]byte, []int) {
	return file_forge_v1_forge_proto_rawDescGZIP(), []int{25}
}

func (x *GetPullRequestDiffResponse) GetDiff() string {
	if x != nil {
		return x.Diff
	}
	return ""
}

type ListReviewsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PullRequest   *PullRequestRef        `protobuf:"bytes,1,opt,name=pull_request,json=pullRequest,proto3" json:"pull_request,omitempty"`
	SinceId       int64                  `protobuf:"varint,2,opt,name=since_id,json=sinceId,proto3" json:"since_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReviewsRequest) Reset() {
	*x = ListReviewsRequest{}
	mi := &file_forge_v1_forge_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReviewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReviewsRequest) ProtoMessage() {}

func (x *ListReviewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_forge_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReviewsRequest.ProtoReflect.Descriptor instead.
func (*ListReviewsRequest) Descriptor() ([]byte, []int) {
	return file_forge_v1_forge_proto_rawDescGZIP(), []int{26}
}

func (x *ListReviewsRequest) GetPullRequest() *PullRequestRef {
	if x != nil {
		return x.PullRequest
	}
	return nil
}

func (x *ListReviewsRequest) GetSinceId() int64 {
	if x != nil {
		return x.SinceId
	}
	return 0
}

type Review struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	SubmittedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Review) Reset() {
	*x = Review{}
	mi := &file_forge_v1_forge_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Review) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Review) ProtoMessage() {}

func (x *Review) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_forge_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Review.ProtoReflect.Descriptor instead.
func (*Review) Descriptor() ([]byte, []int) {
	return file_forge_v1_forge_proto_rawDescGZIP(), []int{27}
}

func (x *Review) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Review) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Review) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Review) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Review) GetSubmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SubmittedAt
	}
	return nil
}

type ListReviewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reviews       []*Review              `protobuf:"bytes,1,rep,name=reviews,proto3" json:"reviews,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReviewsResponse) Reset() {
	*x = ListReviewsResponse{}
	mi := &file_forge_v1_forge_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReviewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReviewsResponse) ProtoMessage() {}

func (x *ListReviewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_forge_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReviewsResponse.ProtoReflect.Descriptor instead.
func (*ListReviewsResponse) Descriptor() ([]byte, []int) {
	return file_forge_v1_forge_proto_rawDescGZIP(), []int{28}
}

func (x *ListReviewsResponse) GetReviews() []*Review {
	if x != nil {
		return x.Reviews
	}
	return nil
}

type ReviewComment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ReviewId      int64                  `protobuf:"varint,2,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Path          string                 `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	Line          int32                  `protobuf:"varint,6,opt,name=line,proto3" json:"line,omitempty"`
	InReplyTo     int64                  `protobuf:"varint,7,opt,name=in_reply_to,json=inReplyTo,proto3" json:"in_reply_to,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewComment) Reset() {
	*x = ReviewComment{}
	mi := &file_forge_v1_forge_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewComment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewComment) ProtoMessage() {}

func (x *ReviewComment) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_forge_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewComment.ProtoReflect.Descriptor instead.
func (*ReviewComment) Descriptor() ([]byte, []int) {
	return file_forge_v1_forge_proto_rawDescGZIP(), []int{29}
}

func (x *ReviewComment) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReviewComment) GetReviewId() int64 {
	if x != nil {
		return x.ReviewId
	}
	return 0
}

func (x *ReviewComment) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *ReviewComment) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *ReviewComment) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ReviewComment) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *ReviewComment) GetInReplyTo() int64 {
	if x != nil {
		return x.InReplyTo
	}
	return 0
}

func (x *ReviewComment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListReviewCommentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PullRequest   *PullRequestRef        `protobuf:"bytes,1,opt,name=pull_request,json=pullRequest,proto3" json:"pull_request,omitempty"`
	SinceId       int64                  `protobuf:"varint,2,opt,name=since_id,json=sinceId,proto3" json:"since_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReviewCommentsRequest) Reset() {
	*x = ListReviewCommentsRequest{}
	mi := &file_forge_v1_forge_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReviewCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReviewCommentsRequest) ProtoMessage() {}

func (x *ListReviewCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_forge_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReviewCommentsRequest.ProtoReflect.Descriptor instead.
func (*ListReviewCommentsRequest) Descriptor() ([]byte, []int) {
	return file_forge_v1_forge_proto_rawDescGZIP(), []int{30}
}

func (x *ListReviewCommentsRequest) GetPullRequest() *PullRequestRef {
	if x != nil {
		return x.PullRequest
	}
	return nil
}

func (x *ListReviewCommentsRequest) GetSinceId() int64 {
	if x != nil {
		return x.SinceId
	}
	return 0
}

type ListReviewCommentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*ReviewComment       `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReviewCommentsResponse) Reset() {
	*x = ListReviewCommentsResponse{}
	mi := &file_forge_v1_forge_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReviewCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReviewCommentsResponse) ProtoMessage() {}

func (x *ListReviewCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_forge_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReviewCommentsResponse.ProtoReflect.Descriptor instead.
func (*ListReviewCommentsResponse) Descriptor() ([]byte, []int) {
	return file_forge_v1_forge_proto_rawDescGZIP(), []int{31}
}

func (x *ListReviewCommentsResponse) GetComments() []*ReviewComment {
	if x != nil {
		return x.Comments
	}
	return nil
}

type ReplyToReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PullRequest   *PullRequestRef        `protobuf:"bytes,1,opt,name=pull_request,json=pullRequest,proto3" json:"pull_request,omitempty"`
	CommentId     int64                  `protobuf:"varint,2,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyToReviewRequest) Reset() {
	*x = ReplyToReviewRequest{}
	mi := &file_forge_v1_forge_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyToReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyToReviewRequest) ProtoMessage() {}

func (x *ReplyToReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_forge_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyToReviewRequest.ProtoReflect.Descriptor instead.
func (*ReplyToReviewRequest) Descriptor() ([]byte, []int) {
	return file_forge_v1_forge_proto_rawDescGZIP(), []int{32}
}

func (x *ReplyToReviewRequest) GetPullRequest() *PullRequestRef {
	if x != nil {
		return x.PullRequest
	}
	return nil
}

func (x *ReplyToReviewRequest) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *ReplyToReviewRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type ReplyToReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyToReviewResponse) Reset() {
	*x = ReplyToReviewResponse{}
	mi := &file_forge_v1_forge_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyToReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyToReviewResponse) ProtoMessage() {}

func (x *ReplyToReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_forge_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyToReviewResponse.ProtoReflect.Descriptor instead.
func (*ReplyToReviewResponse) Descriptor() ([]byte, []int) {
	return file_forge_v1_forge_proto_rawDescGZIP(), []int{33}
}

type InlineReviewComment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Line          int32                  `protobuf:"varint,2,opt,name=line,proto3" json:"line,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InlineReviewComment) Reset() {
	*x = InlineReviewComment{}
	mi := &file_forge_v1_forge_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InlineReviewComment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InlineReviewComment) ProtoMessage() {}

func (x *InlineReviewComment) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_forge_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InlineReviewComment.ProtoReflect.Descriptor instead.
func (*InlineReviewComment) Descriptor() ([]byte, []int) {
	return file_forge_v1_forge_proto_rawDescGZIP(), []int{34}
}

func (x *InlineReviewComment) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *InlineReviewComment) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *InlineReviewComment) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type CreateReviewCommentsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PullRequest     *PullRequestRef        `protobuf:"bytes,1,opt,name=pull_request,json=pullRequest,proto3" json:"pull_request,omitempty"`
	ReviewedHeadSha string                 `protobuf:"bytes,2,opt,name=reviewed_head_sha,json=reviewedHeadSha,proto3" json:"reviewed_head_sha,omitempty"`
	Comments        []*InlineReviewComment `protobuf:"bytes,3,rep,name=comments,proto3" json:"comments,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateReviewCommentsRequest) Reset() {
	*x = CreateReviewCommentsRequest{}
	mi := &file_forge_v1_forge_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReviewCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReviewCommentsRequest) ProtoMessage() {}

func (x *CreateReviewCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_forge_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReviewCommentsRequest.ProtoReflect.Descriptor instead.
func (*CreateReviewCommentsRequest) Descriptor() ([]byte, []int) {
	return file_forge_v1_forge_proto_rawDescGZIP(), []int{35}
}

func (x *CreateReviewCommentsRequest) GetPullRequest() *PullRequestRef {
	if x != nil {
		return x.PullRequest
	}
	return nil
}

func (x *CreateReviewCommentsRequest) GetReviewedHeadSha() string {
	if x != nil {
		return x.ReviewedHeadSha
	}
	return ""
}

func (x *CreateReviewCommentsRequest) GetComments() []*InlineReviewComment {
	if x != nil {
		return x.Comments
	}
	return nil
}

type CreateReviewCommentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReviewCommentsResponse) Reset() {
	*x = CreateReviewCommentsResponse{}
	mi := &file_forge_v1_forge_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReviewCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReviewCommentsResponse) ProtoMessage() {}

func (x *CreateReviewCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_forge_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReviewCommentsResponse.ProtoReflect.Descriptor instead.
func (*CreateReviewCommentsResponse) Descriptor() ([]byte, []int) {
	return file_forge_v1_forge_proto_rawDescGZIP(), []int{36}
}

type LinkBranchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          *RepoRef               `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	IssueNumber   int32                  `protobuf:"varint,2,opt,name=issue_number,json=issueNumber,proto3" json:"issue_number,omitempty"`
	Branch        string                 `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkBranchRequest) Reset() {
	*x = LinkBranchRequest{}
	mi := &file_forge_v1_forge_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkBranchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkBranchRequest) ProtoMessage() {}

func (x *LinkBranchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_forge_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkBranchRequest.ProtoReflect.Descriptor instead.
func (*LinkBranchRequest) Descriptor() ([]byte, []int) {
	return file_forge_v1_forge_proto_rawDescGZIP(), []int{37}
}

func (x *LinkBranchRequest) GetRepo() *RepoRef {
	if x != nil {
		return x.Repo
	}
	return nil
}

func (x *LinkBranchRequest) GetIssueNumber() int32 {
	if x != nil {
		return x.IssueNumber
	}
	return 0
}

func (x *LinkBranchRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

type LinkBranchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkBranchResponse) Reset() {
	*x = LinkBranchResponse{}
	mi := &file_forge_v1_forge_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkBranchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkBranchResponse) ProtoMessage() {}

func (x *LinkBranchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_forge_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkBranchResponse.ProtoReflect.Descriptor instead.
func (*LinkBranchResponse) Descriptor() ([]byte, []int) {
	return file_forge_v1_forge_proto_rawDescGZIP(), []int{38}
}

type AcceptInvitationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptInvitationsRequest) Reset() {
	*x = AcceptInvitationsRequest{}
	mi := &file_forge_v1_forge_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptInvitationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptInvitationsRequest) ProtoMessage() {}

func (x *AcceptInvitationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_forge_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptInvitationsRequest.ProtoReflect.Descriptor instead.
func (*AcceptInvitationsRequest) Descriptor() ([]byte, []int) {
	return file_forge_v1_forge_proto_rawDescGZIP(), []int{39}
}

type AcceptInvitationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptInvitationsResponse) Reset() {
	*x = AcceptInvitationsResponse{}
	mi := &file_forge_v1_forge_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptInvitationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptInvitationsResponse) ProtoMessage() {}

func (x *AcceptInvitationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_forge_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptInvitationsResponse.ProtoReflect.Descriptor instead.
func (*AcceptInvitationsResponse) Descriptor() ([]byte, []int) {
	return file_forge_v1_forge_proto_rawDescGZIP(), []int{40}
}

type VerifyPushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          *RepoRef               `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPushRequest) Reset() {
	*x = VerifyPushRequest{}
	mi := &file_forge_v1_forge_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPushRequest) ProtoMessage() {}

func (x *VerifyPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_forge_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPushRequest.ProtoReflect.Descriptor instead.
func (*VerifyPushRequest) Descriptor() ([]byte, []int) {
	return file_forge_v1_forge_proto_rawDescGZIP(), []int{41}
}

func (x *VerifyPushRequest) GetRepo() *RepoRef {
	if x != nil {
		return x.Repo
	}
	return nil
}

type VerifyPushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPushResponse) Reset() {
	*x = VerifyPushResponse{}
	mi := &file_forge_v1_forge_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPushResponse) ProtoMessage() {}

func (x *VerifyPushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_forge_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPushResponse.ProtoReflect.Descriptor instead.
func (*VerifyPushResponse) Descriptor() ([]byte, []int) {
	return file_forge_v1_forge_proto_rawDescGZIP(), []int{42}
}

type GetRepoArchiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          *RepoRef               `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Ref           string                 `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepoArchiveRequest) Reset() {
	*x = GetRepoArchiveRequest{}
	mi := &file_forge_v1_forge_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepoArchiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepoArchiveRequest) ProtoMessage() {}

func (x *GetRepoArchiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_forge_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepoArchiveRequest.ProtoReflect.Descriptor instead.
func (*GetRepoArchiveRequest) Descriptor() ([]byte, []int) {
	return file_forge_v1_forge_proto_rawDescGZIP(), []int{43}
}

func (x *GetRepoArchiveRequest) GetRepo() *RepoRef {
	if x != nil {
		return x.Repo
	}
	return nil
}

func (x *GetRepoArchiveRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

type GetRepoArchiveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepoArchiveResponse) Reset() {
	*x = GetRepoArchiveResponse{}
	mi := &file_forge_v1_forge_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepoArchiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepoArchiveResponse) ProtoMessage() {}

func (x *GetRepoArchiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forge_v1_forge_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepoArchiveResponse.ProtoReflect.Descriptor instead.
func (*GetRepoArchiveResponse) Descriptor() ([]byte, []int) {
	return file_forge_v1_forge_proto_rawDescGZIP(), []int{44}
}

func (x *GetRepoArchiveResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_forge_v1_forge_proto protoreflect.FileDescriptor

const file_forge_v1_forge_proto_rawDesc = "" +
	"\n" +
	"\x14forge/v1/forge.proto\x12\bforge.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbf\x01\n" +
	"\x10ConfigureRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12D\n" +
	"\bsettings\x18\x03 \x03(\v2(.forge.v1.ConfigureRequest.SettingsEntryR\bsettings\x1a;\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x13\n" +
	"\x11ConfigureResponse\"3\n" +
	"\aRepoRef\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\"O\n" +
	"\x0ePullRequestRef\x12%\n" +
	"\x04repo\x18\x01 \x01(\v2\x11.forge.v1.RepoRefR\x04repo\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x05R\x06number\"a\n" +
	"\x05Issue\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x16\n" +
	"\x06labels\x18\x04 \x03(\tR\x06labels\"A\n" +
	"\x16AssignedIssuesResponse\x12'\n" +
	"\x06issues\x18\x01 \x03(\v2\x0f.forge.v1.IssueR\x06issues\"B\n" +
	"\x17IssuesWithLabelResponse\x12'\n" +
	"\x06issues\x18\x01 \x03(\v2\x0f.forge.v1.IssueR\x06issues\"Z\n" +
	"\x15AssignedIssuesRequest\x12%\n" +
	"\x04repo\x18\x01 \x01(\v2\x11.forge.v1.RepoRefR\x04repo\x12\x1a\n" +
	"\bassignee\x18\x02 \x01(\tR\bassignee\"U\n" +
	"\x16IssuesWithLabelRequest\x12%\n" +
	"\x04repo\x18\x01 \x01(\v2\x11.forge.v1.RepoRefR\x04repo\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"c\n" +
	"\x0eCommentRequest\x12%\n" +
	"\x04repo\x18\x01 \x01(\v2\x11.forge.v1.RepoRefR\x04repo\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x05R\x06number\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\"!\n" +
	"\x0fCommentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"l\n" +
	"\x11CloseIssueRequest\x12%\n" +
	"\x04repo\x18\x01 \x01(\v2\x11.forge.v1.RepoRefR\x04repo\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x05R\x06number\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\"\x14\n" +
	"\x12CloseIssueResponse\"i\n" +
	"\fReactRequest\x12%\n" +
	"\x04repo\x18\x01 \x01(\v2\x11.forge.v1.RepoRefR\x04repo\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x05R\x06number\x12\x1a\n" +
	"\breaction\x18\x03 \x01(\tR\breaction\"\x0f\n" +
	"\rReactResponse\"\x8e\x01\n" +
	"\x14SetStateLabelRequest\x12%\n" +
	"\x04repo\x18\x01 \x01(\v2\x11.forge.v1.RepoRefR\x04repo\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x05R\x06number\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12!\n" +
	"\fknown_labels\x18\x04 \x03(\tR\vknownLabels\"\x17\n" +
	"\x15SetStateLabelResponse\"\x8a\x01\n" +
	"\x0fCreatePRRequest\x12%\n" +
	"\x04repo\x18\x01 \x01(\v2\x11.forge.v1.RepoRefR\x04repo\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04head\x18\x03 \x01(\tR\x04head\x12\x12\n" +
	"\x04base\x18\x04 \x01(\tR\x04base\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\"*\n" +
	"\x10CreatePRResponse\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\"O\n" +
	"\x0ePRStateRequest\x12%\n" +
	"\x04repo\x18\x01 \x01(\v2\x11.forge.v1.RepoRefR\x04repo\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x05R\x06number\"'\n" +
	"\x0fPRStateResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\"\xd1\x01\n" +
	"\vPullRequest\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x19\n" +
	"\bhead_ref\x18\x04 \x01(\tR\aheadRef\x12\x19\n" +
	"\bbase_ref\x18\x05 \x01(\tR\abaseRef\x12\x19\n" +
	"\bhead_sha\x18\x06 \x01(\tR\aheadSha\x12\x19\n" +
	"\bbase_sha\x18\a \x01(\tR\abaseSha\x12\x14\n" +
	"\x05state\x18\b \x01(\tR\x05state\"V\n" +
	"\x15GetPullRequestRequest\x12%\n" +
	"\x04repo\x18\x01 \x01(\v2\x11.forge.v1.RepoRefR\x04repo\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x05R\x06number\"R\n" +
	"\x16GetPullRequestResponse\x128\n" +
	"\fpull_request\x18\x01 \x01(\v2\x15.forge.v1.PullRequestR\vpullRequest\"Z\n" +
	"\x19GetPullRequestDiffRequest\x12%\n" +
	"\x04repo\x18\x01 \x01(\v2\x11.forge.v1.RepoRefR\x04repo\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x05R\x06number\"0\n" +
	"\x1aGetPullRequestDiffResponse\x12\x12\n" +
	"\x04diff\x18\x01 \x01(\tR\x04diff\"l\n" +
	"\x12ListReviewsRequest\x12;\n" +
	"\fpull_request\x18\x01 \x01(\v2\x18.forge.v1.PullRequestRefR\vpullRequest\x12\x19\n" +
	"\bsince_id\x18\x02 \x01(\x03R\asinceId\"\x99\x01\n" +
	"\x06Review\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12=\n" +
	"\fsubmitted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vsubmittedAt\"A\n" +
	"\x13ListReviewsResponse\x12*\n" +
	"\areviews\x18\x01 \x03(\v2\x10.forge.v1.ReviewR\areviews\"\xeb\x01\n" +
	"\rReviewComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\treview_id\x18\x02 \x01(\x03R\breviewId\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\x12\x12\n" +
	"\x04line\x18\x06 \x01(\x05R\x04line\x12\x1e\n" +
	"\vin_reply_to\x18\a \x01(\x03R\tinReplyTo\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"s\n" +
	"\x19ListReviewCommentsRequest\x12;\n" +
	"\fpull_request\x18\x01 \x01(\v2\x18.forge.v1.PullRequestRefR\vpullRequest\x12\x19\n" +
	"\bsince_id\x18\x02 \x01(\x03R\asinceId\"Q\n" +
	"\x1aListReviewCommentsResponse\x123\n" +
	"\bcomments\x18\x01 \x03(\v2\x17.forge.v1.ReviewCommentR\bcomments\"\x86\x01\n" +
	"\x14ReplyToReviewRequest\x12;\n" +
	"\fpull_request\x18\x01 \x01(\v2\x18.forge.v1.PullRequestRefR\vpullRequest\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x02 \x01(\x03R\tcommentId\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\"\x17\n" +
	"\x15ReplyToReviewResponse\"Q\n" +
	"\x13InlineReviewComment\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04line\x18\x02 \x01(\x05R\x04line\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\"\xc1\x01\n" +
	"\x1bCreateReviewCommentsRequest\x12;\n" +
	"\fpull_request\x18\x01 \x01(\v2\x18.forge.v1.PullRequestRefR\vpullRequest\x12*\n" +
	"\x11reviewed_head_sha\x18\x02 \x01(\tR\x0freviewedHeadSha\x129\n" +
	"\bcomments\x18\x03 \x03(\v2\x1d.forge.v1.InlineReviewCommentR\bcomments\"\x1e\n" +
	"\x1cCreateReviewCommentsResponse\"u\n" +
	"\x11LinkBranchRequest\x12%\n" +
	"\x04repo\x18\x01 \x01(\v2\x11.forge.v1.RepoRefR\x04repo\x12!\n" +
	"\fissue_number\x18\x02 \x01(\x05R\vissueNumber\x12\x16\n" +
	"\x06branch\x18\x03 \x01(\tR\x06branch\"\x14\n" +
	"\x12LinkBranchResponse\"\x1a\n" +
	"\x18AcceptInvitationsRequest\"\x1b\n" +
	"\x19AcceptInvitationsResponse\":\n" +
	"\x11VerifyPushRequest\x12%\n" +
	"\x04repo\x18\x01 \x01(\v2\x11.forge.v1.RepoRefR\x04repo\"\x14\n" +
	"\x12VerifyPushResponse\"P\n" +
	"\x15GetRepoArchiveRequest\x12%\n" +
	"\x04repo\x18\x01 \x01(\v2\x11.forge.v1.RepoRefR\x04repo\x12\x10\n" +
	"\x03ref\x18\x02 \x01(\tR\x03ref\",\n" +
	"\x16GetRepoArchiveResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data2\xfc\v\n" +
	"\fForgeService\x12D\n" +
	"\tConfigure\x12\x1a.forge.v1.ConfigureRequest\x1a\x1b.forge.v1.ConfigureResponse\x12S\n" +
	"\x0eAssignedIssues\x12\x1f.forge.v1.AssignedIssuesRequest\x1a .forge.v1.AssignedIssuesResponse\x12V\n" +
	"\x0fIssuesWithLabel\x12 .forge.v1.IssuesWithLabelRequest\x1a!.forge.v1.IssuesWithLabelResponse\x12>\n" +
	"\aComment\x12\x18.forge.v1.CommentRequest\x1a\x19.forge.v1.CommentResponse\x12G\n" +
	"\n" +
	"CloseIssue\x12\x1b.forge.v1.CloseIssueRequest\x1a\x1c.forge.v1.CloseIssueResponse\x128\n" +
	"\x05React\x12\x16.forge.v1.ReactRequest\x1a\x17.forge.v1.ReactResponse\x12P\n" +
	"\rSetStateLabel\x12\x1e.forge.v1.SetStateLabelRequest\x1a\x1f.forge.v1.SetStateLabelResponse\x12A\n" +
	"\bCreatePR\x12\x19.forge.v1.CreatePRRequest\x1a\x1a.forge.v1.CreatePRResponse\x12>\n" +
	"\aPRState\x12\x18.forge.v1.PRStateRequest\x1a\x19.forge.v1.PRStateResponse\x12S\n" +
	"\x0eGetPullRequest\x12\x1f.forge.v1.GetPullRequestRequest\x1a .forge.v1.GetPullRequestResponse\x12_\n" +
	"\x12GetPullRequestDiff\x12#.forge.v1.GetPullRequestDiffRequest\x1a$.forge.v1.GetPullRequestDiffResponse\x12J\n" +
	"\vListReviews\x12\x1c.forge.v1.ListReviewsRequest\x1a\x1d.forge.v1.ListReviewsResponse\x12_\n" +
	"\x12ListReviewComments\x12#.forge.v1.ListReviewCommentsRequest\x1a$.forge.v1.ListReviewCommentsResponse\x12P\n" +
	"\rReplyToReview\x12\x1e.forge.v1.ReplyToReviewRequest\x1a\x1f.forge.v1.ReplyToReviewResponse\x12e\n" +
	"\x14CreateReviewComments\x12%.forge.v1.CreateReviewCommentsRequest\x1a&.forge.v1.CreateReviewCommentsResponse\x12\\\n" +
	"\x11AcceptInvitations\x12\".forge.v1.AcceptInvitationsRequest\x1a#.forge.v1.AcceptInvitationsResponse\x12G\n" +
	"\n" +
	"VerifyPush\x12\x1b.forge.v1.VerifyPushRequest\x1a\x1c.forge.v1.VerifyPushResponse\x12G\n" +
	"\n" +
	"LinkBranch\x12\x1b.forge.v1.LinkBranchRequest\x1a\x1c.forge.v1.LinkBranchResponse\x12U\n" +
	"\x0eGetRepoArchive\x12\x1f.forge.v1.GetRepoArchiveRequest\x1a .forge.v1.GetRepoArchiveResponse0\x01B\x95\x01\n" +
	"\fcom.forge.v1B\n" +
	"ForgeProtoP\x01Z8github.com/samcharles93/archipelago/sdk/forge/v1;forgev1\xa2\x02\x03FXX\xaa\x02\bForge.V1\xca\x02\bForge\\V1\xe2\x02\x14Forge\\V1\\GPBMetadata\xea\x02\tForge::V1b\x06proto3"

var (
	file_forge_v1_forge_proto_rawDescOnce sync.Once
	file_forge_v1_forge_proto_rawDescData []byte
)

func file_forge_v1_forge_proto_rawDescGZIP() []byte {
	file_forge_v1_forge_proto_rawDescOnce.Do(func() {
		file_forge_v1_forge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_forge_v1_forge_proto_rawDesc), len(file_forge_v1_forge_proto_rawDesc)))
	})
	return file_forge_v1_forge_proto_rawDescData
}

var file_forge_v1_forge_proto_msgTypes = make([]protoimpl.MessageInfo, 46)
var file_forge_v1_forge_proto_goTypes = []any{
	(*ConfigureRequest)(nil),             // 0: forge.v1.ConfigureRequest
	(*ConfigureResponse)(nil),            // 1: forge.v1.ConfigureResponse
	(*RepoRef)(nil),                      // 2: forge.v1.RepoRef
	(*PullRequestRef)(nil),               // 3: forge.v1.PullRequestRef
	(*Issue)(nil),                        // 4: forge.v1.Issue
	(*AssignedIssuesResponse)(nil),       // 5: forge.v1.AssignedIssuesResponse
	(*IssuesWithLabelResponse)(nil),      // 6: forge.v1.IssuesWithLabelResponse
	(*AssignedIssuesRequest)(nil),        // 7: forge.v1.AssignedIssuesRequest
	(*IssuesWithLabelRequest)(nil),       // 8: forge.v1.IssuesWithLabelRequest
	(*CommentRequest)(nil),               // 9: forge.v1.CommentRequest
	(*CommentResponse)(nil),              // 10: forge.v1.CommentResponse
	(*CloseIssueRequest)(nil),            // 11: forge.v1.CloseIssueRequest
	(*CloseIssueResponse)(nil),           // 12: forge.v1.CloseIssueResponse
	(*ReactRequest)(nil),                 // 13: forge.v1.ReactRequest
	(*ReactResponse)(nil),                // 14: forge.v1.ReactResponse
	(*SetStateLabelRequest)(nil),         // 15: forge.v1.SetStateLabelRequest
	(*SetStateLabelResponse)(nil),        // 16: forge.v1.SetStateLabelResponse
	(*CreatePRRequest)(nil),              // 17: forge.v1.CreatePRRequest
	(*CreatePRResponse)(nil),             // 18: forge.v1.CreatePRResponse
	(*PRStateRequest)(nil),               // 19: forge.v1.PRStateRequest
	(*PRStateResponse)(nil),              // 20: forge.v1.PRStateResponse
	(*PullRequest)(nil),                  // 21: forge.v1.PullRequest
	(*GetPullRequestRequest)(nil),        // 22: forge.v1.GetPullRequestRequest
	(*GetPullRequestResponse)(nil),       // 23: forge.v1.GetPullRequestResponse
	(*GetPullRequestDiffRequest)(nil),    // 24: forge.v1.GetPullRequestDiffRequest
	(*GetPullRequestDiffResponse)(nil),   // 25: forge.v1.GetPullRequestDiffResponse
	(*ListReviewsRequest)(nil),           // 26: forge.v1.ListReviewsRequest
	(*Review)(nil),                       // 27: forge.v1.Review
	(*ListReviewsResponse)(nil),          // 28: forge.v1.ListReviewsResponse
	(*ReviewComment)(nil),                // 29: forge.v1.ReviewComment
	(*ListReviewCommentsRequest)(nil),    // 30: forge.v1.ListReviewCommentsRequest
	(*ListReviewCommentsResponse)(nil),   // 31: forge.v1.ListReviewCommentsResponse
	(*ReplyToReviewRequest)(nil),         // 32: forge.v1.ReplyToReviewRequest
	(*ReplyToReviewResponse)(nil),        // 33: forge.v1.ReplyToReviewResponse
	(*InlineReviewComment)(nil),          // 34: forge.v1.InlineReviewComment
	(*CreateReviewCommentsRequest)(nil),  // 35: forge.v1.CreateReviewCommentsRequest
	(*CreateReviewCommentsResponse)(nil), // 36: forge.v1.CreateReviewCommentsResponse
	(*LinkBranchRequest)(nil),            // 37: forge.v1.LinkBranchRequest
	(*LinkBranchResponse)(nil),           // 38: forge.v1.LinkBranchResponse
	(*AcceptInvitationsRequest)(nil),     // 39: forge.v1.AcceptInvitationsRequest
	(*AcceptInvitationsResponse)(nil),    // 40: forge.v1.AcceptInvitationsResponse
	(*VerifyPushRequest)(nil),            // 41: forge.v1.VerifyPushRequest
	(*VerifyPushResponse)(nil),           // 42: forge.v1.VerifyPushResponse
	(*GetRepoArchiveRequest)(nil),        // 43: forge.v1.GetRepoArchiveRequest
	(*GetRepoArchiveResponse)(nil),       // 44: forge.v1.GetRepoArchiveResponse
	nil,                                  // 45: forge.v1.ConfigureRequest.SettingsEntry
	(*timestamppb.Timestamp)(nil),        // 46: google.protobuf.Timestamp
}
var file_forge_v1_forge_proto_depIdxs = []int32{
	45, // 0: forge.v1.ConfigureRequest.settings:type_name -> forge.v1.ConfigureRequest.SettingsEntry
	2,  // 1: forge.v1.PullRequestRef.repo:type_name -> forge.v1.RepoRef
	4,  // 2: forge.v1.AssignedIssuesResponse.issues:type_name -> forge.v1.Issue
	4,  // 3: forge.v1.IssuesWithLabelResponse.issues:type_name -> forge.v1.Issue
	2,  // 4: forge.v1.AssignedIssuesRequest.repo:type_name -> forge.v1.RepoRef
	2,  // 5: forge.v1.IssuesWithLabelRequest.repo:type_name -> forge.v1.RepoRef
	2,  // 6: forge.v1.CommentRequest.repo:type_name -> forge.v1.RepoRef
	2,  // 7: forge.v1.CloseIssueRequest.repo:type_name -> forge.v1.RepoRef
	2,  // 8: forge.v1.ReactRequest.repo:type_name -> forge.v1.RepoRef
	2,  // 9: forge.v1.SetStateLabelRequest.repo:type_name -> forge.v1.RepoRef
	2,  // 10: forge.v1.CreatePRRequest.repo:type_name -> forge.v1.RepoRef
	2,  // 11: forge.v1.PRStateRequest.repo:type_name -> forge.v1.RepoRef
	2,  // 12: forge.v1.GetPullRequestRequest.repo:type_name -> forge.v1.RepoRef
	21, // 13: forge.v1.GetPullRequestResponse.pull_request:type_name -> forge.v1.PullRequest
	2,  // 14: forge.v1.GetPullRequestDiffRequest.repo:type_name -> forge.v1.RepoRef
	3,  // 15: forge.v1.ListReviewsRequest.pull_request:type_name -> forge.v1.PullRequestRef
	46, // 16: forge.v1.Review.submitted_at:type_name -> google.protobuf.Timestamp
	27, // 17: forge.v1.ListReviewsResponse.reviews:type_name -> forge.v1.Review
	46, // 18: forge.v1.ReviewComment.created_at:type_name -> google.protobuf.Timestamp
	3,  // 19: forge.v1.ListReviewCommentsRequest.pull_request:type_name -> forge.v1.PullRequestRef
	29, // 20: forge.v1.ListReviewCommentsResponse.comments:type_name -> forge.v1.ReviewComment
	3,  // 21: forge.v1.ReplyToReviewRequest.pull_request:type_name -> forge.v1.PullRequestRef
	3,  // 22: forge.v1.CreateReviewCommentsRequest.pull_request:type_name -> forge.v1.PullRequestRef
	34, // 23: forge.v1.CreateReviewCommentsRequest.comments:type_name -> forge.v1.InlineReviewComment
	2,  // 24: forge.v1.LinkBranchRequest.repo:type_name -> forge.v1.RepoRef
	2,  // 25: forge.v1.VerifyPushRequest.repo:type_name -> forge.v1.RepoRef
	2,  // 26: forge.v1.GetRepoArchiveRequest.repo:type_name -> forge.v1.RepoRef
	0,  // 27: forge.v1.ForgeService.Configure:input_type -> forge.v1.ConfigureRequest
	7,  // 28: forge.v1.ForgeService.AssignedIssues:input_type -> forge.v1.AssignedIssuesRequest
	8,  // 29: forge.v1.ForgeService.IssuesWithLabel:input_type -> forge.v1.IssuesWithLabelRequest
	9,  // 30: forge.v1.ForgeService.Comment:input_type -> forge.v1.CommentRequest
	11, // 31: forge.v1.ForgeService.CloseIssue:input_type -> forge.v1.CloseIssueRequest
	13, // 32: forge.v1.ForgeService.React:input_type -> forge.v1.ReactRequest
	15, // 33: forge.v1.ForgeService.SetStateLabel:input_type -> forge.v1.SetStateLabelRequest
	17, // 34: forge.v1.ForgeService.CreatePR:input_type -> forge.v1.CreatePRRequest
	19, // 35: forge.v1.ForgeService.PRState:input_type -> forge.v1.PRStateRequest
	22, // 36: forge.v1.ForgeService.GetPullRequest:input_type -> forge.v1.GetPullRequestRequest
	24, // 37: forge.v1.ForgeService.GetPullRequestDiff:input_type -> forge.v1.GetPullRequestDiffRequest
	26, // 38: forge.v1.ForgeService.ListReviews:input_type -> forge.v1.ListReviewsRequest
	30, // 39: forge.v1.ForgeService.ListReviewComments:input_type -> forge.v1.ListReviewCommentsRequest
	32, // 40: forge.v1.ForgeService.ReplyToReview:input_type -> forge.v1.ReplyToReviewRequest
	35, // 41: forge.v1.ForgeService.CreateReviewComments:input_type -> forge.v1.CreateReviewCommentsRequest
	39, // 42: forge.v1.ForgeService.AcceptInvitations:input_type -> forge.v1.AcceptInvitationsRequest
	41, // 43: forge.v1.ForgeService.VerifyPush:input_type -> forge.v1.VerifyPushRequest
	37, // 44: forge.v1.ForgeService.LinkBranch:input_type -> forge.v1.LinkBranchRequest
	43, // 45: forge.v1.ForgeService.GetRepoArchive:input_type -> forge.v1.GetRepoArchiveRequest
	1,  // 46: forge.v1.ForgeService.Configure:output_type -> forge.v1.ConfigureResponse
	5,  // 47: forge.v1.ForgeService.AssignedIssues:output_type -> forge.v1.AssignedIssuesResponse
	6,  // 48: forge.v1.ForgeService.IssuesWithLabel:output_type -> forge.v1.IssuesWithLabelResponse
	10, // 49: forge.v1.ForgeService.Comment:output_type -> forge.v1.CommentResponse
	12, // 50: forge.v1.ForgeService.CloseIssue:output_type -> forge.v1.CloseIssueResponse
	14, // 51: forge.v1.ForgeService.React:output_type -> forge.v1.ReactResponse
	16, // 52: forge.v1.ForgeService.SetStateLabel:output_type -> forge.v1.SetStateLabelResponse
	18, // 53: forge.v1.ForgeService.CreatePR:output_type -> forge.v1.CreatePRResponse
	20, // 54: forge.v1.ForgeService.PRState:output_type -> forge.v1.PRStateResponse
	23, // 55: forge.v1.ForgeService.GetPullRequest:output_type -> forge.v1.GetPullRequestResponse
	25, // 56: forge.v1.ForgeService.GetPullRequestDiff:output_type -> forge.v1.GetPullRequestDiffResponse
	28, // 57: forge.v1.ForgeService.ListReviews:output_type -> forge.v1.ListReviewsResponse
	31, // 58: forge.v1.ForgeService.ListReviewComments:output_type -> forge.v1.ListReviewCommentsResponse
	33, // 59: forge.v1.ForgeService.ReplyToReview:output_type -> forge.v1.ReplyToReviewResponse
	36, // 60: forge.v1.ForgeService.CreateReviewComments:output_type -> forge.v1.CreateReviewCommentsResponse
	40, // 61: forge.v1.ForgeService.AcceptInvitations:output_type -> forge.v1.AcceptInvitationsResponse
	42, // 62: forge.v1.ForgeService.VerifyPush:output_type -> forge.v1.VerifyPushResponse
	38, // 63: forge.v1.ForgeService.LinkBranch:output_type -> forge.v1.LinkBranchResponse
	44, // 64: forge.v1.ForgeService.GetRepoArchive:output_type -> forge.v1.GetRepoArchiveResponse
	46, // [46:65] is the sub-list for method output_type
	27, // [27:46] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_forge_v1_forge_proto_init() }
func file_forge_v1_forge_proto_init() {
	if File_forge_v1_forge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_forge_v1_forge_proto_rawDesc), len(file_forge_v1_forge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   46,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_forge_v1_forge_proto_goTypes,
		DependencyIndexes: file_forge_v1_forge_proto_depIdxs,
		MessageInfos:      file_forge_v1_forge_proto_msgTypes,
	}.Build()
	File_forge_v1_forge_proto = out.File
	file_forge_v1_forge_proto_goTypes = nil
	file_forge_v1_forge_proto_depIdxs = nil
}
