// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: secretengine/v1/secretengine.proto

package secretenginev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SecretEngineService_Configure_FullMethodName = "/secretengine.v1.SecretEngineService/Configure"
	SecretEngineService_Resolve_FullMethodName   = "/secretengine.v1.SecretEngineService/Resolve"
)

// SecretEngineServiceClient is the client API for SecretEngineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SecretEngineService is the surface a secret-engine extension serves. The
// host launches one plugin process per enabled engine and resolves every
// SecretRef naming that engine through it.
type SecretEngineServiceClient interface {
	// Configure hands the engine its settings once, right after launch and
	// before any Resolve. It is the only channel for configuration: the plugin
	// process does not inherit the host environment.
	Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error)
	// Resolve returns the value for key. An unknown key is NOT_FOUND.
	Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error)
}

type secretEngineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSecretEngineServiceClient(cc grpc.ClientConnInterface) SecretEngineServiceClient {
	return &secretEngineServiceClient{cc}
}

func (c *secretEngineServiceClient) Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureResponse)
	err := c.cc.Invoke(ctx, SecretEngineService_Configure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretEngineServiceClient) Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveResponse)
	err := c.cc.Invoke(ctx, SecretEngineService_Resolve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecretEngineServiceServer is the server API for SecretEngineService service.
// All implementations must embed UnimplementedSecretEngineServiceServer
// for forward compatibility.
//
// SecretEngineService is the surface a secret-engine extension serves. The
// host launches one plugin process per enabled engine and resolves every
// SecretRef naming that engine through it.
type SecretEngineServiceServer interface {
	// Configure hands the engine its settings once, right after launch and
	// before any Resolve. It is the only channel for configuration: the plugin
	// process does not inherit the host environment.
	Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error)
	// Resolve returns the value for key. An unknown key is NOT_FOUND.
	Resolve(context.Context, *ResolveRequest) (*ResolveResponse, error)
	mustEmbedUnimplementedSecretEngineServiceServer()
}

// UnimplementedSecretEngineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSecretEngineServiceServer struct{}

func (UnimplementedSecretEngineServiceServer) Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Configure not implemented")
}
func (UnimplementedSecretEngineServiceServer) Resolve(context.Context, *ResolveRequest) (*ResolveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Resolve not implemented")
}
func (UnimplementedSecretEngineServiceServer) mustEmbedUnimplementedSecretEngineServiceServer() {}
func (UnimplementedSecretEngineServiceServer) testEmbeddedByValue()                             {}

// UnsafeSecretEngineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecretEngineServiceServer will
// result in compilation errors.
type UnsafeSecretEngineServiceServer interface {
	mustEmbedUnimplementedSecretEngineServiceServer()
}

func RegisterSecretEngineServiceServer(s grpc.ServiceRegistrar, srv SecretEngineServiceServer) {
	// If the following call panics, it indicates UnimplementedSecretEngineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SecretEngineService_ServiceDesc, srv)
}

func _SecretEngineService_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretEngineServiceServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretEngineService_Configure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretEngineServiceServer).Configure(ctx, req.(*ConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretEngineService_Resolve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretEngineServiceServer).Resolve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretEngineService_Resolve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretEngineServiceServer).Resolve(ctx, req.(*ResolveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SecretEngineService_ServiceDesc is the grpc.ServiceDesc for SecretEngineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SecretEngineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "secretengine.v1.SecretEngineService",
	HandlerType: (*SecretEngineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Configure",
			Handler:    _SecretEngineService_Configure_Handler,
		},
		{
			MethodName: "Resolve",
			Handler:    _SecretEngineService_Resolve_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "secretengine/v1/secretengine.proto",
}
