// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: secretengine/v1/secretengine.proto

package secretenginev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      map[string]string      `protobuf:"bytes,1,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_secretengine_v1_secretengine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secretengine_v1_secretengine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_secretengine_v1_secretengine_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigureRequest) GetSettings() map[string]string {
	if x != nil {
		return x.Settings
	}
	return nil
}

type ConfigureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_secretengine_v1_secretengine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secretengine_v1_secretengine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_secretengine_v1_secretengine_proto_rawDescGZIP(), []int{1}
}

type ResolveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveRequest) Reset() {
	*x = ResolveRequest{}
	mi := &file_secretengine_v1_secretengine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRequest) ProtoMessage() {}

func (x *ResolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secretengine_v1_secretengine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRequest.ProtoReflect.Descriptor instead.
func (*ResolveRequest) Descriptor() ([]byte, []int) {
	return file_secretengine_v1_secretengine_proto_rawDescGZIP(), []int{2}
}

func (x *ResolveRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ResolveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveResponse) Reset() {
	*x = ResolveResponse{}
	mi := &file_secretengine_v1_secretengine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResponse) ProtoMessage() {}

func (x *ResolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secretengine_v1_secretengine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResponse.ProtoReflect.Descriptor instead.
func (*ResolveResponse) Descriptor() ([]byte, []int) {
	return file_secretengine_v1_secretengine_proto_rawDescGZIP(), []int{3}
}

func (x *ResolveResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_secretengine_v1_secretengine_proto protoreflect.FileDescriptor

const file_secretengine_v1_secretengine_proto_rawDesc = "" +
	"\n" +
	"\"secretengine/v1/secretengine.proto\x12\x0fsecretengine.v1\"\x9c\x01\n" +
	"\x10ConfigureRequest\x12K\n" +
	"\bsettings\x18\x01 \x03(\v2/.secretengine.v1.ConfigureRequest.SettingsEntryR\bsettings\x1a;\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x13\n" +
	"\x11ConfigureResponse\"\"\n" +
	"\x0eResolveRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"'\n" +
	"\x0fResolveResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value2\xb7\x01\n" +
	"\x13SecretEngineService\x12R\n" +
	"\tConfigure\x12!.secretengine.v1.ConfigureRequest\x1a\".secretengine.v1.ConfigureResponse\x12L\n" +
	"\aResolve\x12\x1f.secretengine.v1.ResolveRequest\x1a .secretengine.v1.ResolveResponseB\xcd\x01\n" +
	"\x13com.secretengine.v1B\x11SecretengineProtoP\x01ZFgithub.com/samcharles93/archipelago/sdk/secretengine/v1;secretenginev1\xa2\x02\x03SXX\xaa\x02\x0fSecretengine.V1\xca\x02\x0fSecretengine\\V1\xe2\x02\x1bSecretengine\\V1\\GPBMetadata\xea\x02\x10Secretengine::V1b\x06proto3"

var (
	file_secretengine_v1_secretengine_proto_rawDescOnce sync.Once
	file_secretengine_v1_secretengine_proto_rawDescData []byte
)

func file_secretengine_v1_secretengine_proto_rawDescGZIP() []byte {
	file_secretengine_v1_secretengine_proto_rawDescOnce.Do(func() {
		file_secretengine_v1_secretengine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_secretengine_v1_secretengine_proto_rawDesc), len(file_secretengine_v1_secretengine_proto_rawDesc)))
	})
	return file_secretengine_v1_secretengine_proto_rawDescData
}

var file_secretengine_v1_secretengine_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_secretengine_v1_secretengine_proto_goTypes = []any{
	(*ConfigureRequest)(nil),  // 0: secretengine.v1.ConfigureRequest
	(*ConfigureResponse)(nil), // 1: secretengine.v1.ConfigureResponse
	(*ResolveRequest)(nil),    // 2: secretengine.v1.ResolveRequest
	(*ResolveResponse)(nil),   // 3: secretengine.v1.ResolveResponse
	nil,                       // 4: secretengine.v1.ConfigureRequest.SettingsEntry
}
var file_secretengine_v1_secretengine_proto_depIdxs = []int32{
	4, // 0: secretengine.v1.ConfigureRequest.settings:type_name -> secretengine.v1.ConfigureRequest.SettingsEntry
	0, // 1: secretengine.v1.SecretEngineService.Configure:input_type -> secretengine.v1.ConfigureRequest
	2, // 2: secretengine.v1.SecretEngineService.Resolve:input_type -> secretengine.v1.ResolveRequest
	1, // 3: secretengine.v1.SecretEngineService.Configure:output_type -> secretengine.v1.ConfigureResponse
	3, // 4: secretengine.v1.SecretEngineService.Resolve:output_type -> secretengine.v1.ResolveResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_secretengine_v1_secretengine_proto_init() }
func file_secretengine_v1_secretengine_proto_init() {
	if File_secretengine_v1_secretengine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_secretengine_v1_secretengine_proto_rawDesc), len(file_secretengine_v1_secretengine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_secretengine_v1_secretengine_proto_goTypes,
		DependencyIndexes: file_secretengine_v1_secretengine_proto_depIdxs,
		MessageInfos:      file_secretengine_v1_secretengine_proto_msgTypes,
	}.Build()
	File_secretengine_v1_secretengine_proto = out.File
	file_secretengine_v1_secretengine_proto_goTypes = nil
	file_secretengine_v1_secretengine_proto_depIdxs = nil
}
