// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: channel/v1/channel.proto

package channelv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunResponse_State int32

const (
	RunResponse_STATE_UNSPECIFIED RunResponse_State = 0
	RunResponse_STATE_STARTING    RunResponse_State = 1
	RunResponse_STATE_RUNNING     RunResponse_State = 2
)

// Enum value maps for RunResponse_State.
var (
	RunResponse_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_STARTING",
		2: "STATE_RUNNING",
	}
	RunResponse_State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_STARTING":    1,
		"STATE_RUNNING":     2,
	}
)

func (x RunResponse_State) Enum() *RunResponse_State {
	p := new(RunResponse_State)
	*p = x
	return p
}

func (x RunResponse_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RunResponse_State) Descriptor() protoreflect.EnumDescriptor {
	return file_channel_v1_channel_proto_enumTypes[0].Descriptor()
}

func (RunResponse_State) Type() protoreflect.EnumType {
	return &file_channel_v1_channel_proto_enumTypes[0]
}

func (x RunResponse_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RunResponse_State.Descriptor instead.
func (RunResponse_State) EnumDescriptor() ([]byte, []int) {
	return file_channel_v1_channel_proto_rawDescGZIP(), []int{1, 0}
}

type RunRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// settings are the operator's values for this channel from extension
	// settings. A key ending in _ref holds an "engine:key" secret reference the
	// host resolves; the plugin receives the value in secrets, under the key
	// without the suffix.
	Settings map[string]string `protobuf:"bytes,1,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Secrets  map[string]string `protobuf:"bytes,2,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// chat_broker_id is the plugin broker stream the host serves
	// gateway.v1.ChatService on.
	ChatBrokerId  uint32 `protobuf:"varint,3,opt,name=chat_broker_id,json=chatBrokerId,proto3" json:"chat_broker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_channel_v1_channel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_channel_v1_channel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_channel_v1_channel_proto_rawDescGZIP(), []int{0}
}

func (x *RunRequest) GetSettings() map[string]string {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *RunRequest) GetSecrets() map[string]string {
	if x != nil {
		return x.Secrets
	}
	return nil
}

func (x *RunRequest) GetChatBrokerId() uint32 {
	if x != nil {
		return x.ChatBrokerId
	}
	return 0
}

type RunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         RunResponse_State      `protobuf:"varint,1,opt,name=state,proto3,enum=channel.v1.RunResponse_State" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	mi := &file_channel_v1_channel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_channel_v1_channel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_channel_v1_channel_proto_rawDescGZIP(), []int{1}
}

func (x *RunResponse) GetState() RunResponse_State {
	if x != nil {
		return x.State
	}
	return RunResponse_STATE_UNSPECIFIED
}

var File_channel_v1_channel_proto protoreflect.FileDescriptor

const file_channel_v1_channel_proto_rawDesc = "" +
	"\n" +
	"\x18channel/v1/channel.proto\x12\n" +
	"channel.v1\"\xac\x02\n" +
	"\n" +
	"RunRequest\x12@\n" +
	"\bsettings\x18\x01 \x03(\v2$.channel.v1.RunRequest.SettingsEntryR\bsettings\x12=\n" +
	"\asecrets\x18\x02 \x03(\v2#.channel.v1.RunRequest.SecretsEntryR\asecrets\x12$\n" +
	"\x0echat_broker_id\x18\x03 \x01(\rR\fchatBrokerId\x1a;\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fSecretsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x89\x01\n" +
	"\vRunResponse\x123\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1d.channel.v1.RunResponse.StateR\x05state\"E\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATE_STARTING\x10\x01\x12\x11\n" +
	"\rSTATE_RUNNING\x10\x022J\n" +
	"\x0eChannelService\x128\n" +
	"\x03Run\x12\x16.channel.v1.RunRequest\x1a\x17.channel.v1.RunResponse0\x01B\xa5\x01\n" +
	"\x0ecom.channel.v1B\fChannelProtoP\x01Z<github.com/samcharles93/archipelago/sdk/channel/v1;channelv1\xa2\x02\x03CXX\xaa\x02\n" +
	"Channel.V1\xca\x02\n" +
	"Channel\\V1\xe2\x02\x16Channel\\V1\\GPBMetadata\xea\x02\vChannel::V1b\x06proto3"

var (
	file_channel_v1_channel_proto_rawDescOnce sync.Once
	file_channel_v1_channel_proto_rawDescData []byte
)

func file_channel_v1_channel_proto_rawDescGZIP() []byte {
	file_channel_v1_channel_proto_rawDescOnce.Do(func() {
		file_channel_v1_channel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_channel_v1_channel_proto_rawDesc), len(file_channel_v1_channel_proto_rawDesc)))
	})
	return file_channel_v1_channel_proto_rawDescData
}

var file_channel_v1_channel_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_channel_v1_channel_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_channel_v1_channel_proto_goTypes = []any{
	(RunResponse_State)(0), // 0: channel.v1.RunResponse.State
	(*RunRequest)(nil),     // 1: channel.v1.RunRequest
	(*RunResponse)(nil),    // 2: channel.v1.RunResponse
	nil,                    // 3: channel.v1.RunRequest.SettingsEntry
	nil,                    // 4: channel.v1.RunRequest.SecretsEntry
}
var file_channel_v1_channel_proto_depIdxs = []int32{
	3, // 0: channel.v1.RunRequest.settings:type_name -> channel.v1.RunRequest.SettingsEntry
	4, // 1: channel.v1.RunRequest.secrets:type_name -> channel.v1.RunRequest.SecretsEntry
	0, // 2: channel.v1.RunResponse.state:type_name -> channel.v1.RunResponse.State
	1, // 3: channel.v1.ChannelService.Run:input_type -> channel.v1.RunRequest
	2, // 4: channel.v1.ChannelService.Run:output_type -> channel.v1.RunResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_channel_v1_channel_proto_init() }
func file_channel_v1_channel_proto_init() {
	if File_channel_v1_channel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_channel_v1_channel_proto_rawDesc), len(file_channel_v1_channel_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_channel_v1_channel_proto_goTypes,
		DependencyIndexes: file_channel_v1_channel_proto_depIdxs,
		EnumInfos:         file_channel_v1_channel_proto_enumTypes,
		MessageInfos:      file_channel_v1_channel_proto_msgTypes,
	}.Build()
	File_channel_v1_channel_proto = out.File
	file_channel_v1_channel_proto_goTypes = nil
	file_channel_v1_channel_proto_depIdxs = nil
}
